apiVersion: apps/v1
kind: Deployment
metadata:
  name: gen-ai-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: gcr.io/myproject/gen-ai-chatbot
        ports:
        - containerPort: 8000