name: Deploy AI Chatbot

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r api/requirements.txt

      - name: Deploy to GCP
        run: |
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud run deploy chatbot --image=gcr.io/myproject/gen-ai-chatbot --region=us-central1